name: rogier
favicon: null
layout_spectrum: 0.22888722317293286
typography_spectrum: 0.3783181665930897
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#333333'
    - '#f2f2f2'
    - '#08def7'
    - '#62c300'
    - '#0071bc'
  brandStrength: 1
  lightness: 0.5625
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose: []
