name: rogier
favicon: null
layout_spectrum: 0.49673
typography_spectrum: 0.34899
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1c9fd4'
    - '#085892'
    - '#28c8fa'
    - '#f2f2f2'
    - '#333333'
  brandStrength: 1
  lightness: 0.5625
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose: []
